### ISSUE TITLE
Update json-schema-ref-parser

### ISSUE THREAD

**Issue by clementbolin** [byu-oit/openapi-enforcer#129]
Hello,

it's a great work you did, I would however have a small question I noticed that on the master branch you embedded the dependency ```json-schema-ref-parser``` 6.1.0 which itself embeds an old version of ```js-yaml``` containing the lib ```"esprima": "^4.0.0"``` which takes about 500 KB of memory for nothing.I would have liked to know if json-schema-ref-parser was going to be updated since its new version (9.0.9) includes a more recent ```js-yaml``` version that removed ```esprima```.

![image](https://user-images.githubusercontent.com/4447392/139255742-08e819d6-5dff-4439-b341-f48004ddb45b.png)

**Comment by Gi60s** [comment]
Thanks for the information on those changes for submitting the issue. Due to your comments, I've made multiple changes that you can read about in the [changelog](https://github.com/byu-oit/openapi-enforcer/blob/master/CHANGELOG.md).

I appreciate the research you put into this. You'll have to let me know if you see anything else.

The changes are published to npm as version `1.16.0`.
