### ISSUE TITLE
Suppress "Non standard format" warning

### ISSUE THREAD

**Issue by zoellner** [byu-oit/openapi-enforcer#36]
Question:
Is there a way to suppress certain types of warnings?

I get a lot of warnings along the lines of 

          at: 1 > properties
            at: contact > properties
              at: id > format
                Non standard format "uuid" used for type "string"

The specification says
> Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification. 

So I understand that you trigger a warning in this case, but since it is commonly used, I would like to suppress this particular type of warning as it clutters the output too much and makes it hard to spot other warnings. 
Is there a way to do this?

**Comment by Gi60s** [comment]
Currently the system does not have an option to specify which warnings to suppress, although it is possible to suppress this specific type of warning by defining the format you are using.

Defining a format enables the enforcer, telling it how to handle that type and format, so that it knows how to serialize and deserialize, validate, produce a random value, and to identify which other validation properties can be applied (numeric vs non-numeric).

You can see the documentation for this at https://byu-oit.github.io/openapi-enforcer/api/components/schema#definedatatypeformat

If you do build the code for these type and formats for email and UUID I would highly recommend that you build them as NPM packages and publish them so that other developers can use them. If you do build those package please add the keyword `openapi-enforcer` to them and let me know what the packages are named so that I can add them to the documentation.

All that said, what is your opinion? Is that too much work to suppress this warning? You understand now why it is important to define custom type formats. Failure to define the custom format will treat it as the base type (minus format). What are your thoughts?

**Comment by Gi60s** [comment]
Also, it's possible to define the type without rules to serialize, deserialize, etc.

```js
Enforcer.v2_0.Schema.defineDataTypeFormat('string', 'uuid', null);
Enforcer.v3_0.Schema.defineDataTypeFormat('string', 'uuid', null);
```

**Comment by zoellner** [comment]
That makes sense. Thank you for the pointers to the docs. 
If I decide to use openapi-enforcer more extensively I think I'll create some packages for that. For now I'll go with the quick solution.

**Comment by Gi60s** [comment]
I've decided that this is enough of a pain point for people that I added some functionality that allows you to control which warning codes you see. You can check out the documentation at https://byu-oit.github.io/openapi-enforcer/guide/exceptions. The changes are active on NPM with version `1.6.0`.

**Comment by zoellner** [comment]
Thanks for adding this. I'll have a look.
