### ISSUE TITLE
Buffer constructors have been deprecated

### ISSUE THREAD

**Issue by OAFCROB** [byu-oit/openapi-enforcer#79]
**Issue**

Buffer constructors have been deprecated, [see](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/) and we're seeing the following error; 

`ERROR	(node:9) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by Gi60s** [comment]
Thanks for the research and the PR. I've merged the PR, updated the change log, and published to NPM as version `1.10.5`.

Although this change is potentially a breaking change for anyone running old NodeJS, because NodeJS no longer supports any LTS that would be affected I've opted to match this a patch version change.

Thanks again for contributing.

**Comment by OAFCROB** [comment]
No problem, thanks for the great repo 😀
