### ISSUE TITLE
incorrect validation of date-time strings

### ISSUE THREAD

**Issue by mbradburn** [byu-oit/openapi-enforcer#83]
My schema specifies an item of type "string" with a "date-time" format, which the OpenAPI spec should match strings formatted according to RFC3339's "date-time".  However, input validation fails when given such a string:

Err:  [ EnforcerException: Invalid value
    at: date
      Expected a valid date object. Received: "2020-08-13T21:25:25.807Z" ]

... as the code demands a Javascript Date object rather than a string.

[index-js.txt](https://github.com/byu-oit/openapi-enforcer/files/5071562/index-js.txt)

**Comment by Gi60s** [comment]
Hey Matthew. Thanks for the issue.

The `validate` function is actually for validating deserialized values. You can see that in the documentation here: https://byu-oit.github.io/openapi-enforcer/api/components/schema#validate

If you want to validate a serialized value the process would involve calling the deserialize function and then validating that result. This allows you to validate more complex and custom formats. It also allows you to work with native objects instead of their serialized equivalents. A deserialized object can also be serialized using this library prior to sending the data over the internet.

Let me know if you have any questions or other thoughts about this. I'll close this issue for now.

**Comment by Gi60s** [comment]
You probably understand this, but just to add a little clarification. A date string like `'2020-08-13T21:25:25.807Z'` is considered serialized where a date object like `new Date('2020-08-13T21:25:25.807Z')` is considered deserialized. This library makes it easy to transition those states, but validation must happen in the deserialized state.

**Comment by mbradburn** [comment]
Thanks for clearing this up, I think I read that part of the doc but failed to comprehend it. :-)

**Comment by Gi60s** [comment]
Glad I could help.

**Comment by irobson** [comment]
I know it is a bit old, but I wonder how to deserialize a whole object instead of just a single property? I instantiated the enforcer via new Enforcer('../..yaml').
